export const styledComponentSlugs = [
  "agent-handoff",
  "agent-plan",
  "agent-run-timeline",
  "agent-status",
  "approval-gate",
  "approval-request",
  "artifact-preview",
  "citation-popover",
  "citation-ui",
  "code-execution",
  "confidence-answer",
  "context-files",
  "context-picker",
  "context-usage",
  "conversation-sidebar",
  "cost-meter",
  "edit-diff-view",
  "error-message",
  "eval-results",
  "file-upload",
  "generated-media",
  "generative-ui",
  "inline-correction",
  "markdown-message",
  "memory-chip",
  "memory-list",
  "memory-suggestion",
  "memory-toast",
  "message-actions",
  "model-selector",
  "moderation-flag",
  "output-comparison",
  "prompt-editor",
  "prompt-input",
  "prompt-input-attachments",
  "prompt-input-model-selector",
  "reasoning",
  "reasoning-level",
  "reasoning-steps",
  "refusal-message",
  "response-rating",
  "response-versions",
  "search-tool-call",
  "source-card",
  "source-list",
  "streaming-markdown",
  "streaming-message",
  "thinking-indicator",
  "tool-call",
  "tool-toggle",
  "user-message",
  "voice-call-controls",
  "voice-conversation",
  "voice-input",
  "voice-waveform"
] as const;
export type StyledComponentSlug = typeof styledComponentSlugs[number];

export function isStyledComponent(slug: string): slug is StyledComponentSlug {
  return styledComponentSlugs.some((item) => item === slug);
}
