export type ResourceCategory = {
  slug: string;
  name: string;
  description: string;
};

export type ResourceEntry = {
  name: string;
  url: string;
  category: string;
  description: string;
  /** Has a meaningful free tier. */
  free: boolean;
  /** Purpose-built for AI products (vs. general UI that also works). */
  ai_native: boolean;
  source: "official" | "community";
  /** One-line curation note — when to use it, or how it pairs with our components. */
  notes: string;
  tags: string[];
};

export const resourceCategories: ResourceCategory[] = [
  {
    slug: "libraries",
    name: "Component Libraries",
    description: "Component and UI libraries for AI interfaces.",
  },
  {
    slug: "generators",
    name: "AI UI Generators",
    description: "Turn prompts into interfaces and full apps.",
  },
  {
    slug: "design",
    name: "Design Tools",
    description: "Figma kits, mockups and design tooling.",
  },
  {
    slug: "learn",
    name: "Learn & References",
    description: "Guides and research on designing for AI.",
  },
  {
    slug: "assets",
    name: "Icons & Assets",
    description: "Icons, logos and fonts for AI product UI.",
  },
];

export const resources: ResourceEntry[] = [
  /* ---------------------------- Libraries ---------------------------- */
  {
    name: "Vercel AI SDK",
    url: "https://sdk.vercel.ai",
    category: "libraries",
    description:
      "Official React, Vue and Svelte components and hooks for streaming AI responses.",
    free: true,
    ai_native: true,
    source: "official",
    notes:
      "The streaming foundation most React AI apps are built on — pairs well with our visual states on top.",
    tags: ["react", "streaming", "sdk"],
  },
  {
    name: "assistant-ui",
    url: "https://www.assistant-ui.com",
    category: "libraries",
    description: "Open-source toolkit of chat and agent UI components for React.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Drop-in chat canvas with threads, streaming and tools — good for production chat apps.",
    tags: ["react", "chat", "agent", "open-source"],
  },
  {
    name: "CopilotKit",
    url: "https://www.copilotkit.ai",
    category: "libraries",
    description: "Framework for building in-app AI assistants and copilots.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Embed copilots into existing apps rather than building a separate chat surface.",
    tags: ["react", "copilot", "framework"],
  },
  {
    name: "shadcn/ui",
    url: "https://ui.shadcn.com",
    category: "libraries",
    description: "Copy-paste component library that most AI product teams build on.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Not AI-specific, but the baseline stack our copyable components assume.",
    tags: ["react", "tailwind", "radix"],
  },
  {
    name: "Magic UI",
    url: "https://magicui.design",
    category: "libraries",
    description: "Animated components for AI dashboards, agents and landing pages.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Great for motion-rich moments — orbs, beams, spotlight — around AI features.",
    tags: ["react", "animation", "marketing"],
  },
  {
    name: "Aceternity UI",
    url: "https://ui.aceternity.com",
    category: "libraries",
    description: "Modern UI components including agent and AI dashboard sections.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Strong landing-page and dashboard components with a distinctive look.",
    tags: ["react", "components", "dashboard"],
  },
  {
    name: "Flowbite",
    url: "https://flowbite.com",
    category: "libraries",
    description: "Tailwind components including a chat and AI starter kit.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "A quick way to scaffold a chat UI if you are already on Flowbite.",
    tags: ["tailwind", "chat", "components"],
  },
  {
    name: "Radix UI",
    url: "https://www.radix-ui.com",
    category: "libraries",
    description: "Headless, accessible primitives — the foundation under shadcn/ui.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "The unstyled layer most React AI stacks build on; our copyable components assume it indirectly.",
    tags: ["react", "headless", "accessible"],
  },
  {
    name: "Base UI",
    url: "https://www.base-ui.com",
    category: "libraries",
    description: "Unstyled React primitives from MUI, extracted into a standalone library.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "A lighter, React 19-ready alternative to Radix for building custom AI components.",
    tags: ["react", "headless", "mui"],
  },
  {
    name: "HeroUI",
    url: "https://heroui.com",
    category: "libraries",
    description: "Beautifully styled React components with prebuilt AI app templates.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Ships ready-made chat and agent layouts if you want to start closer to finished.",
    tags: ["react", "templates", "chat"],
  },
  {
    name: "Chakra UI",
    url: "https://chakra-ui.com",
    category: "libraries",
    description: "Accessible React component library with a strong theme system.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "A mature design-system base for teams that want theming out of the box.",
    tags: ["react", "design-system", "accessible"],
  },
  {
    name: "Mantine",
    url: "https://mantine.dev",
    category: "libraries",
    description: "Full-featured React component library with over 100 components.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Good for data-dense AI dashboards — tables, overlays and notifications included.",
    tags: ["react", "components", "dashboard"],
  },
  {
    name: "Park UI",
    url: "https://park-ui.com",
    category: "libraries",
    description: "Styled component library built on Ark UI primitives with Tailwind or CSS.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "If you want the shadcn feel but need Ark UI's headless control instead of Radix.",
    tags: ["react", "ark-ui", "tailwind"],
  },
  {
    name: "Headless UI",
    url: "https://headlessui.com",
    category: "libraries",
    description: "Unstyled, accessible components from Tailwind Labs.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Menus, dialogs and popovers with no styling opinion — style to match your AI brand.",
    tags: ["react", "headless", "accessible"],
  },
  {
    name: "DaisyUI",
    url: "https://daisyui.com",
    category: "libraries",
    description: "Component classes that sit on top of Tailwind, no build config needed.",
    free: true,
    ai_native: false,
    source: "community",
    notes: "The fastest way to prototype with Tailwind if you don't want a React library.",
    tags: ["tailwind", "classes", "css"],
  },

  /* ---------------------------- Generators --------------------------- */
  {
    name: "v0",
    url: "https://v0.dev",
    category: "generators",
    description: "Generate UI components and pages from text prompts (Vercel).",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Fastest path from an idea to a working React + Tailwind interface.",
    tags: ["generator", "react", "tailwind", "vercel"],
  },
  {
    name: "Galileo AI",
    url: "https://www.galileo.ai",
    category: "generators",
    description: "Generate high-fidelity UI designs from text prompts.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Best when you want polished visuals to start a design, not a working app.",
    tags: ["generator", "design", "figma"],
  },
  {
    name: "Lovable",
    url: "https://lovable.dev",
    category: "generators",
    description: "AI app builder that turns prompts into full products.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "For founders shipping an MVP end-to-end without writing much code.",
    tags: ["generator", "app-builder", "mvp"],
  },
  {
    name: "Bolt.new",
    url: "https://bolt.new",
    category: "generators",
    description: "Prompt-to-fullstack-app generation in the browser.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Runs the whole stack — frontend, backend, deploy — from one prompt.",
    tags: ["generator", "fullstack", "stackblitz"],
  },
  {
    name: "Cursor",
    url: "https://cursor.com",
    category: "generators",
    description: "AI-first code editor that builds interfaces in code.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "The coding-agent UI this site's coding-agent pattern is modeled on.",
    tags: ["editor", "coding-agent", "claude"],
  },
  {
    name: "Replit Agent",
    url: "https://replit.com",
    category: "generators",
    description: "Build, host and deploy apps by prompting.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Lowest-friction way to go from idea to a hosted app in minutes.",
    tags: ["generator", "app-builder", "deploy"],
  },
  {
    name: "Claude",
    url: "https://claude.ai",
    category: "generators",
    description: "Generate interface code directly in Artifacts and Projects.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Excellent at producing single-file components — pair it with our copyable code.",
    tags: ["generator", "artifacts", "claude"],
  },
  {
    name: "Framer AI",
    url: "https://www.framer.com",
    category: "generators",
    description: "AI site builder with a visual editor and instant publishing.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "For marketing sites and landing pages with AI-generated sections.",
    tags: ["generator", "landing-page", "visual-editor"],
  },
  {
    name: "Gemini",
    url: "https://gemini.google.com",
    category: "generators",
    description: "Google's AI assistant that can generate and run simple web apps.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Good for quick canvas-style prototypes that run live in the conversation.",
    tags: ["generator", "google", "canvas"],
  },
  {
    name: "Windsurf",
    url: "https://windsurf.com",
    category: "generators",
    description: "Agentic AI IDE that builds and edits interfaces in context.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Cascade flows like Cursor's agent mode — handy for editing this site's patterns.",
    tags: ["editor", "coding-agent", "ide"],
  },
  {
    name: "GitHub Copilot",
    url: "https://github.com/features/copilot",
    category: "generators",
    description: "AI pair programmer with an agent mode inside VS Code and the web.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Agent mode can scaffold a component from a screenshot or description.",
    tags: ["editor", "pair-programming", "vscode"],
  },
  {
    name: "Figma Make",
    url: "https://www.figma.com/ai",
    category: "generators",
    description: "Figma's AI features for generating and editing designs in context.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Design-stage generation — pair it with our React code for the implementation half.",
    tags: ["figma", "design", "ai"],
  },
  {
    name: "Wix Studio",
    url: "https://www.wix.com/studio",
    category: "generators",
    description: "AI site-building platform aimed at agencies and professional creators.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "For AI-generated marketing sites with more design control than a pure prompt tool.",
    tags: ["generator", "sites", "agencies"],
  },
  {
    name: "Google AI Studio",
    url: "https://aistudio.google.com",
    category: "generators",
    description: "Prototype and generate interfaces with the Gemini API, free in the browser.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "The quickest sandbox for prompt-to-code prototypes with live model preview.",
    tags: ["prototyping", "gemini", "prompt"],
  },

  /* ---------------------------- Design Tools -------------------------- */
  {
    name: "Figma Community",
    url: "https://www.figma.com/community",
    category: "design",
    description: "Search 'AI UI' for free kits, plugins and AI product templates.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "The place to find AI UI kits and plugins — a good complement to our React components.",
    tags: ["figma", "kits", "plugins"],
  },
  {
    name: "Untitled UI",
    url: "https://www.untitledui.com",
    category: "design",
    description: "UI kit and design system with AI product components.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Polished, consistent design system — handy as a layer under AI-specific screens.",
    tags: ["figma", "design-system", "ui-kit"],
  },
  {
    name: "Anima",
    url: "https://www.animaapp.com",
    category: "design",
    description: "Figma-to-code with AI, including a 'Design with AI' mode.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Bridges the Figma-to-React gap if your team designs before coding.",
    tags: ["figma", "code", "ai"],
  },
  {
    name: "Relume",
    url: "https://www.relume.io",
    category: "design",
    description: "AI sitemaps, wireframes and copy for marketing pages.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Great for structuring an AI product's landing page before any visual design.",
    tags: ["sitemap", "wireframe", "marketing"],
  },
  {
    name: "Excalidraw",
    url: "https://excalidraw.com",
    category: "design",
    description: "Free whiteboard for sketching interface flows and states.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Sketch conversation flows and edge states before touching code.",
    tags: ["whiteboard", "sketch", "free"],
  },
  {
    name: "Penpot",
    url: "https://penpot.app",
    category: "design",
    description: "Open-source design and prototyping tool — a Figma alternative.",
    free: true,
    ai_native: false,
    source: "community",
    notes: "Self-hostable design tooling for teams that want full control of their files.",
    tags: ["open-source", "prototyping", "figma-alternative"],
  },
  {
    name: "Miro",
    url: "https://miro.com",
    category: "design",
    description: "Infinite-canvas whiteboard for mapping AI product flows and states.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Map conversation flows, approval paths and error states before building.",
    tags: ["whiteboard", "flows", "diagramming"],
  },
  {
    name: "FigJam",
    url: "https://www.figma.com/figjam",
    category: "design",
    description: "Figma's collaborative diagramming tool for UX flows and workshops.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Sketch chat flows and agent loops with the same teams already in Figma.",
    tags: ["diagramming", "flows", "figma"],
  },
  {
    name: "Maze",
    url: "https://maze.co",
    category: "design",
    description: "Rapid prototype testing with actionable UX insights.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Validate an AI onboarding or conversation flow before committing to code.",
    tags: ["testing", "prototype", "research"],
  },
  {
    name: "Stark",
    url: "https://www.getstark.co",
    category: "design",
    description: "Accessibility toolkit for design and development workflows.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Catch contrast and reading issues early — especially with AI-generated text surfaces.",
    tags: ["accessibility", "contrast", "tools"],
  },
  {
    name: "Wireframe.cc",
    url: "https://wireframe.cc",
    category: "design",
    description: "Minimal browser wireframing with a beautifully simple editor.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Layout the skeleton of an AI screen in seconds with zero setup.",
    tags: ["wireframe", "sketch", "low-fidelity"],
  },

  /* ------------------------------ Learn ------------------------------- */
  {
    name: "Anthropic — Claude Docs & UX",
    url: "https://www.anthropic.com",
    category: "learn",
    description: "Product guidance and best practices for designing with Claude.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "First-party guidance on streaming, tool use and agent UX from the model maker.",
    tags: ["docs", "ux", "claude"],
  },
  {
    name: "Nielsen Norman Group",
    url: "https://www.nngroup.com",
    category: "learn",
    description: "Evidence-based research on chatbots, AI UX and agent interfaces.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "The most-cited research on how people actually use conversational UIs.",
    tags: ["research", "ux", "usability"],
  },
  {
    name: "Vercel AI Engineering",
    url: "https://vercel.com/blog",
    category: "learn",
    description: "Engineering posts on streaming, AI UI and building with the AI SDK.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Practical, current writing on the streaming patterns behind AI apps.",
    tags: ["blog", "streaming", "engineering"],
  },
  {
    name: "Google People + AI Guidebook",
    url: "https://pair.withgoogle.com",
    category: "learn",
    description: "Patterns for human-centered AI design from Google PAIR.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "A durable reference for explaining AI capability and handling errors gracefully.",
    tags: ["guidebook", "human-centered", "patterns"],
  },
  {
    name: "OpenAI Docs",
    url: "https://platform.openai.com/docs",
    category: "learn",
    description: "API and product guidance, including UI patterns for model interaction.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Useful for the protocol side — how streaming, tools and reasoning arrive.",
    tags: ["docs", "api", "streaming"],
  },
  {
    name: "a16z AI Essays",
    url: "https://a16z.com",
    category: "learn",
    description: "Strategy essays on AI products, interfaces and the evolving stack.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Context for why AI UI patterns are shifting — good background reading.",
    tags: ["essays", "strategy", "ai"],
  },
  {
    name: "Microsoft HAX Toolkit",
    url: "https://www.microsoft.com/en-us/haxtoolkit",
    category: "learn",
    description: "Design toolkit for human-AI interaction, from Microsoft Research.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Pattern cards for explaining AI, handling failure and making capabilities legible.",
    tags: ["research", "toolkit", "human-ai"],
  },
  {
    name: "Elements of AI",
    url: "https://www.elementsofai.com",
    category: "learn",
    description: "Free university-level course on AI basics for non-specialists.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Grounds your team's mental model of what the UI is actually controlling.",
    tags: ["course", "free", "foundations"],
  },
  {
    name: "Prompting Guide",
    url: "https://www.promptingguide.ai",
    category: "learn",
    description: "Community guide to prompt engineering patterns and techniques.",
    free: true,
    ai_native: true,
    source: "community",
    notes: "Understand what your users' prompts are doing under the hood.",
    tags: ["prompts", "patterns", "guide"],
  },
  {
    name: "Hugging Face Docs",
    url: "https://huggingface.co/docs",
    category: "learn",
    description: "Documentation for models, tools and inference APIs.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Reference for model capabilities that UI states must reflect.",
    tags: ["docs", "models", "inference"],
  },
  {
    name: "Latent Space",
    url: "https://www.latent.space",
    category: "learn",
    description: "Newsletter and podcast on AI engineering and the people building it.",
    free: true,
    ai_native: true,
    source: "community",
    notes: "First-hand accounts of how shipped AI products design their UX.",
    tags: ["newsletter", "podcast", "engineering"],
  },
  {
    name: "Superlinear",
    url: "https://www.superlinear.academy",
    category: "learn",
    description: "Teardowns and strategies from AI product builders.",
    free: true,
    ai_native: true,
    source: "community",
    notes: "Close readings of shipped AI apps — a natural next step from this site's inspiration section.",
    tags: ["teardowns", "case-studies", "products"],
  },

  /* ------------------------------ Assets ------------------------------ */
  {
    name: "Lucide",
    url: "https://lucide.dev",
    category: "assets",
    description: "Open-source icon set widely used across AI interfaces.",
    free: true,
    ai_native: false,
    source: "community",
    notes: "Clean, consistent icons for toolbars, statuses and actions.",
    tags: ["icons", "open-source", "svg"],
  },
  {
    name: "Simple Icons",
    url: "https://simpleicons.org",
    category: "assets",
    description: "Brand logos including model providers like OpenAI and Anthropic.",
    free: true,
    ai_native: false,
    source: "community",
    notes: "When your UI needs recognizable provider or tool logos.",
    tags: ["logos", "brands", "svg"],
  },
  {
    name: "Geist",
    url: "https://vercel.com/font",
    category: "assets",
    description: "Vercel's font family — the clean UI typeface this site uses.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "A tasteful default typeface for product UI, with matching mono.",
    tags: ["font", "typography", "vercel"],
  },
  {
    name: "Heroicons",
    url: "https://heroicons.com",
    category: "assets",
    description: "Hand-crafted SVG icons from Tailwind Labs.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Friendly outline icons that slot into any Tailwind interface.",
    tags: ["icons", "svg", "tailwind"],
  },
  {
    name: "Iconify",
    url: "https://iconify.design",
    category: "assets",
    description: "Browse and serve 100,000+ icons from one unified API.",
    free: true,
    ai_native: false,
    source: "community",
    notes: "One consistent icon layer across many sets — handy for AI tool icons.",
    tags: ["icons", "api", "svg"],
  },
  {
    name: "Phosphor Icons",
    url: "https://phosphoricons.com",
    category: "assets",
    description: "Six weight-based icon families with a friendly, consistent look.",
    free: true,
    ai_native: false,
    source: "community",
    notes: "Thin-to-fill weights make status changes read clearly in agent UIs.",
    tags: ["icons", "svg", "weights"],
  },
  {
    name: "Tabler Icons",
    url: "https://tabler.io/icons",
    category: "assets",
    description: "4,900+ crisp line icons available as SVG and React components.",
    free: true,
    ai_native: false,
    source: "community",
    notes: "A deep set of generic UI icons with search built in.",
    tags: ["icons", "svg", "react"],
  },
  {
    name: "Google Fonts",
    url: "https://fonts.google.com",
    category: "assets",
    description: "Free fonts for web and product UI, including the Geist family.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Pick a legible UI face and a mono for tool payloads and code.",
    tags: ["fonts", "typography", "free"],
  },
  {
    name: "Fontsource",
    url: "https://fontsource.org",
    category: "assets",
    description: "Self-hosted, dependency-free font packages for npm projects.",
    free: true,
    ai_native: false,
    source: "community",
    notes: "Ship fonts with your app instead of paying the render-blocking cost of a CDN.",
    tags: ["fonts", "npm", "self-hosted"],
  },
  {
    name: "Open Peeps",
    url: "https://www.openpeeps.com",
    category: "assets",
    description: "Hand-drawn, editable illustration library in a single file.",
    free: true,
    ai_native: false,
    source: "community",
    notes: "Friendly characters for AI onboarding, empty states and illustration.",
    tags: ["illustrations", "empty-states", "free"],
  },
];

export function getResourceCategory(slug: string) {
  return resourceCategories.find((c) => c.slug === slug);
}
