export type ResourceCategory = {
  slug: string;
  name: string;
  description: string;
};

export type ResourceEntry = {
  name: string;
  url: string;
  category: string;
  description: string;
  /** Has a meaningful free tier. */
  free: boolean;
  /** Purpose-built for AI products (vs. general UI that also works). */
  ai_native: boolean;
  source: "official" | "community";
  /** One-line curation note — when to use it, or how it pairs with our components. */
  notes: string;
  tags: string[];
};

export const resourceCategories: ResourceCategory[] = [
  {
    slug: "libraries",
    name: "Component Libraries",
    description: "Component and UI libraries for AI interfaces.",
  },
  {
    slug: "generators",
    name: "AI UI Generators",
    description: "Turn prompts into interfaces and full apps.",
  },
  {
    slug: "design",
    name: "Design Tools",
    description: "Figma kits, mockups and design tooling.",
  },
  {
    slug: "learn",
    name: "Learn & References",
    description: "Guides and research on designing for AI.",
  },
  {
    slug: "assets",
    name: "Icons & Assets",
    description: "Icons, logos and fonts for AI product UI.",
  },
];

export const resources: ResourceEntry[] = [
  /* ---------------------------- Libraries ---------------------------- */
  {
    name: "Vercel AI SDK",
    url: "https://sdk.vercel.ai",
    category: "libraries",
    description:
      "Official React, Vue and Svelte components and hooks for streaming AI responses.",
    free: true,
    ai_native: true,
    source: "official",
    notes:
      "The streaming foundation most React AI apps are built on — pairs well with our visual states on top.",
    tags: ["react", "streaming", "sdk"],
  },
  {
    name: "assistant-ui",
    url: "https://www.assistant-ui.com",
    category: "libraries",
    description: "Open-source toolkit of chat and agent UI components for React.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Drop-in chat canvas with threads, streaming and tools — good for production chat apps.",
    tags: ["react", "chat", "agent", "open-source"],
  },
  {
    name: "CopilotKit",
    url: "https://www.copilotkit.ai",
    category: "libraries",
    description: "Framework for building in-app AI assistants and copilots.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Embed copilots into existing apps rather than building a separate chat surface.",
    tags: ["react", "copilot", "framework"],
  },
  {
    name: "shadcn/ui",
    url: "https://ui.shadcn.com",
    category: "libraries",
    description: "Copy-paste component library that most AI product teams build on.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Not AI-specific, but the baseline stack our copyable components assume.",
    tags: ["react", "tailwind", "radix"],
  },
  {
    name: "Magic UI",
    url: "https://magicui.design",
    category: "libraries",
    description: "Animated components for AI dashboards, agents and landing pages.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Great for motion-rich moments — orbs, beams, spotlight — around AI features.",
    tags: ["react", "animation", "marketing"],
  },
  {
    name: "Aceternity UI",
    url: "https://ui.aceternity.com",
    category: "libraries",
    description: "Modern UI components including agent and AI dashboard sections.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Strong landing-page and dashboard components with a distinctive look.",
    tags: ["react", "components", "dashboard"],
  },
  {
    name: "Flowbite",
    url: "https://flowbite.com",
    category: "libraries",
    description: "Tailwind components including a chat and AI starter kit.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "A quick way to scaffold a chat UI if you are already on Flowbite.",
    tags: ["tailwind", "chat", "components"],
  },

  /* ---------------------------- Generators --------------------------- */
  {
    name: "v0",
    url: "https://v0.dev",
    category: "generators",
    description: "Generate UI components and pages from text prompts (Vercel).",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Fastest path from an idea to a working React + Tailwind interface.",
    tags: ["generator", "react", "tailwind", "vercel"],
  },
  {
    name: "Galileo AI",
    url: "https://www.galileo.ai",
    category: "generators",
    description: "Generate high-fidelity UI designs from text prompts.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Best when you want polished visuals to start a design, not a working app.",
    tags: ["generator", "design", "figma"],
  },
  {
    name: "Lovable",
    url: "https://lovable.dev",
    category: "generators",
    description: "AI app builder that turns prompts into full products.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "For founders shipping an MVP end-to-end without writing much code.",
    tags: ["generator", "app-builder", "mvp"],
  },
  {
    name: "Bolt.new",
    url: "https://bolt.new",
    category: "generators",
    description: "Prompt-to-fullstack-app generation in the browser.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Runs the whole stack — frontend, backend, deploy — from one prompt.",
    tags: ["generator", "fullstack", "stackblitz"],
  },
  {
    name: "Cursor",
    url: "https://cursor.com",
    category: "generators",
    description: "AI-first code editor that builds interfaces in code.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "The coding-agent UI this site's coding-agent pattern is modeled on.",
    tags: ["editor", "coding-agent", "claude"],
  },
  {
    name: "Replit Agent",
    url: "https://replit.com",
    category: "generators",
    description: "Build, host and deploy apps by prompting.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Lowest-friction way to go from idea to a hosted app in minutes.",
    tags: ["generator", "app-builder", "deploy"],
  },
  {
    name: "Claude",
    url: "https://claude.ai",
    category: "generators",
    description: "Generate interface code directly in Artifacts and Projects.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Excellent at producing single-file components — pair it with our copyable code.",
    tags: ["generator", "artifacts", "claude"],
  },
  {
    name: "Framer AI",
    url: "https://www.framer.com",
    category: "generators",
    description: "AI site builder with a visual editor and instant publishing.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "For marketing sites and landing pages with AI-generated sections.",
    tags: ["generator", "landing-page", "visual-editor"],
  },

  /* ---------------------------- Design Tools -------------------------- */
  {
    name: "Figma Community",
    url: "https://www.figma.com/community",
    category: "design",
    description: "Search 'AI UI' for free kits, plugins and AI product templates.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "The place to find AI UI kits and plugins — a good complement to our React components.",
    tags: ["figma", "kits", "plugins"],
  },
  {
    name: "Untitled UI",
    url: "https://www.untitledui.com",
    category: "design",
    description: "UI kit and design system with AI product components.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Polished, consistent design system — handy as a layer under AI-specific screens.",
    tags: ["figma", "design-system", "ui-kit"],
  },
  {
    name: "Anima",
    url: "https://www.animaapp.com",
    category: "design",
    description: "Figma-to-code with AI, including a 'Design with AI' mode.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Bridges the Figma-to-React gap if your team designs before coding.",
    tags: ["figma", "code", "ai"],
  },
  {
    name: "Relume",
    url: "https://www.relume.io",
    category: "design",
    description: "AI sitemaps, wireframes and copy for marketing pages.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Great for structuring an AI product's landing page before any visual design.",
    tags: ["sitemap", "wireframe", "marketing"],
  },
  {
    name: "Excalidraw",
    url: "https://excalidraw.com",
    category: "design",
    description: "Free whiteboard for sketching interface flows and states.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Sketch conversation flows and edge states before touching code.",
    tags: ["whiteboard", "sketch", "free"],
  },

  /* ------------------------------ Learn ------------------------------- */
  {
    name: "Anthropic — Claude Docs & UX",
    url: "https://www.anthropic.com",
    category: "learn",
    description: "Product guidance and best practices for designing with Claude.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "First-party guidance on streaming, tool use and agent UX from the model maker.",
    tags: ["docs", "ux", "claude"],
  },
  {
    name: "Nielsen Norman Group",
    url: "https://www.nngroup.com",
    category: "learn",
    description: "Evidence-based research on chatbots, AI UX and agent interfaces.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "The most-cited research on how people actually use conversational UIs.",
    tags: ["research", "ux", "usability"],
  },
  {
    name: "Vercel AI Engineering",
    url: "https://vercel.com/blog",
    category: "learn",
    description: "Engineering posts on streaming, AI UI and building with the AI SDK.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Practical, current writing on the streaming patterns behind AI apps.",
    tags: ["blog", "streaming", "engineering"],
  },
  {
    name: "Google People + AI Guidebook",
    url: "https://pair.withgoogle.com",
    category: "learn",
    description: "Patterns for human-centered AI design from Google PAIR.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "A durable reference for explaining AI capability and handling errors gracefully.",
    tags: ["guidebook", "human-centered", "patterns"],
  },
  {
    name: "OpenAI Docs",
    url: "https://platform.openai.com/docs",
    category: "learn",
    description: "API and product guidance, including UI patterns for model interaction.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Useful for the protocol side — how streaming, tools and reasoning arrive.",
    tags: ["docs", "api", "streaming"],
  },
  {
    name: "a16z AI Essays",
    url: "https://a16z.com",
    category: "learn",
    description: "Strategy essays on AI products, interfaces and the evolving stack.",
    free: true,
    ai_native: true,
    source: "official",
    notes: "Context for why AI UI patterns are shifting — good background reading.",
    tags: ["essays", "strategy", "ai"],
  },

  /* ------------------------------ Assets ------------------------------ */
  {
    name: "Lucide",
    url: "https://lucide.dev",
    category: "assets",
    description: "Open-source icon set widely used across AI interfaces.",
    free: true,
    ai_native: false,
    source: "community",
    notes: "Clean, consistent icons for toolbars, statuses and actions.",
    tags: ["icons", "open-source", "svg"],
  },
  {
    name: "Simple Icons",
    url: "https://simpleicons.org",
    category: "assets",
    description: "Brand logos including model providers like OpenAI and Anthropic.",
    free: true,
    ai_native: false,
    source: "community",
    notes: "When your UI needs recognizable provider or tool logos.",
    tags: ["logos", "brands", "svg"],
  },
  {
    name: "Geist",
    url: "https://vercel.com/font",
    category: "assets",
    description: "Vercel's font family — the clean UI typeface this site uses.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "A tasteful default typeface for product UI, with matching mono.",
    tags: ["font", "typography", "vercel"],
  },
  {
    name: "Heroicons",
    url: "https://heroicons.com",
    category: "assets",
    description: "Hand-crafted SVG icons from Tailwind Labs.",
    free: true,
    ai_native: false,
    source: "official",
    notes: "Friendly outline icons that slot into any Tailwind interface.",
    tags: ["icons", "svg", "tailwind"],
  },
];

export function getResourceCategory(slug: string) {
  return resourceCategories.find((c) => c.slug === slug);
}
